Repository HemantNegi/jquery.sumoselect, pull requests merged in 2021-06, with the labels that each got.

#270 Fix change event not being registered by addEventListener
  docs/images/Thumbs.db
  docs/images/body-bg.jpg
  docs/images/download-button.png
  docs/images/github-button.png
  docs/images/header-bg.jpg
  docs/images/highlight-bg.jpg
  docs/images/sidebar-bg.jpg
  docs/index.html
  docs/javascripts/jquery.sumoselect.js
  docs/javascripts/jquery.sumoselect.min.js
  docs/javascripts/main.js
  docs/params.json
  docs/select_responsive.html
  docs/stylesheets/print.css
  docs/stylesheets/pygment_trac.css
  docs/stylesheets/stylesheet.css
  docs/stylesheets/sumoselect.css
  docs/sumoselect_demo.html
  jquery.sumoselect.js
  jquery.sumoselect.min.js
Labels: enhancement

#199 fix toggSelAll - fire just one change-event on original select element
  jquery.sumoselect.js
Labels: bug

#280 Adding sumo:initialized sumo:unloaded events
  README.md
  jquery.sumoselect.js
Labels: Modifications needed, invalid
